spring.application.name=nodes

spring.datasource.url=jdbc:postgresql://dpg-cvptnn1r0fns73881co0-a.oregon-postgres.render.com:5432/nodes_db
spring.datasource.username=nodes_db_user
spring.datasource.password=ZG6pckukEK7hdlqIagXqtwsqyXj1WI1K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect